-- Ctastenotreate tables
DROP TABLE IF EXISTS Hop;
DROP TABLE IF EXISTS Fermentable;
DROP TABLE IF EXISTS Misc;
DROP TABLE IF EXISTS Yeast;
DROP TABLE IF EXISTS Style;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS MashStep;
DROP TABLE IF EXISTS Mash;
DROP TABLE IF EXISTS Water;
DROP TABLE IF EXISTS Recipe;
